### ISSUE TITLE
No Gold

### ISSUE THREAD

**Issue by ALittlePixie** [OpenThrone/OpenThrone#250] opened 2024-10-03 15:41 UTC
I'm not getting gold every half hour.

**Comment by GroupTherapyPT** [comment] 2024-10-03 16:02
yeah me too, no income in the last 3 turns.

**Comment by ALittlePixie** [comment] 2024-10-03 16:34
I think it's now been 5 turns for me. - Arwen

**Comment by NunosDC** [comment] 2024-10-03 20:18
We are aware of the problem and are working on a permanent solution and some back of house tools that will allow us to push out missed turned based event fixes.

**Comment by uaktags** [comment] 2024-10-04 00:55
the issue is multifaceted:
- Our db provider provides only so many connections for the connection pool
- the auto-recruiter doesn't have a session based limitation in place (auto-recruiter is only a dev-mode feature and is not going to be part of the full release)
- users are running multiple windows (in some instances 5-6 windows) to do their auto-recruiting which is saturating the db connection pool
- we need to increase the timeout on db calls, but doing so may exacerbate the issue due to the above causes
- we need to implement a cron/scheduled task tracker to find when tasks fail to execute and retry them either as a whole or on a per-user basis.

I have pieces of a fix in place, but still working on how to tackle the issue as a whole. The next patch will most likely only be the cron tracker and db timeout, but there may be needs to disable auto-recruiting or apply guards, but again without too much dev time being dedicated to it.

**Comment by uaktags** [comment] 2024-11-03 02:38
forgot to close this out

**Closed by uaktags** 2024-11-03 02:38 UTC
Labels: fixed - awaiting deployment
